export type VehicleStatus = 'ativo' | 'em_manutencao' | 'inativo' | 'reservado' | 'indisponivel'
export type DocumentStatus = 'em_dia' | 'proximo' | 'vencido'
export type TripStatus = 'em_andamento' | 'concluida' | 'cancelada'
export type MaintenanceStatus = 'aberta' | 'em_andamento' | 'concluida' | 'cancelada'
export type MaintenanceType = 'preventiva' | 'corretiva'
export type Severity = 'baixa' | 'atencao' | 'critica'
