declare module '@prodexy/ui' {
  import * as React from 'react'
  type AnyProps = React.PropsWithChildren<any>
  export const Button: React.FC<AnyProps>
  export const Badge: React.FC<AnyProps>
  export const Card: React.FC<AnyProps>
  export const CardHeader: React.FC<AnyProps>
  export const CardTitle: React.FC<AnyProps>
  export const CardDescription: React.FC<AnyProps>
  export const CardContent: React.FC<AnyProps>
  export const CardFooter: React.FC<AnyProps>
  export const Checkbox: React.FC<AnyProps>
  export const Table: React.FC<AnyProps>
  export const TableHeader: React.FC<AnyProps>
  export const TableBody: React.FC<AnyProps>
  export const TableFooter: React.FC<AnyProps>
  export const TableHead: React.FC<AnyProps>
  export const TableRow: React.FC<AnyProps>
  export const TableCell: React.FC<AnyProps>
  export const Tabs: React.FC<AnyProps>
  export const TabsList: React.FC<AnyProps>
  export const TabsTrigger: React.FC<AnyProps>
  export const TabsContent: React.FC<AnyProps>
  export const Dialog: React.FC<AnyProps>
  export const DialogContent: React.FC<AnyProps>
  export const DialogHeader: React.FC<AnyProps>
  export const DialogTitle: React.FC<AnyProps>
  export const DialogDescription: React.FC<AnyProps>
  export const Sheet: React.FC<AnyProps>
  export const SheetContent: React.FC<AnyProps>
  export const SheetHeader: React.FC<AnyProps>
  export const SheetTitle: React.FC<AnyProps>
  export const SheetDescription: React.FC<AnyProps>
  export const SheetTrigger: React.FC<AnyProps>
  export const Select: React.FC<AnyProps>
  export const SelectContent: React.FC<AnyProps>
  export const SelectGroup: React.FC<AnyProps>
  export const SelectItem: React.FC<AnyProps>
  export const SelectLabel: React.FC<AnyProps>
  export const SelectScrollDownButton: React.FC<AnyProps>
  export const SelectScrollUpButton: React.FC<AnyProps>
  export const SelectSeparator: React.FC<AnyProps>
  export const SelectTrigger: React.FC<AnyProps>
  export const SelectValue: React.FC<AnyProps>
  export const Input: React.FC<AnyProps>
  export const Label: React.FC<AnyProps>
  export const Textarea: React.FC<AnyProps>
  export function cn(...inputs: any[]): string
}
